### ISSUE TITLE
X11 Error while Running jmavsim with remote window fowarding.

### ISSUE THREAD

**Issue by owenalpha** [DrTon/jMAVSim#36]
I'm getting an odd error with jmavsim, but only when running remotely using x11 forwarding. Any suggestions much appreciated.

Command:
 java -Djava.ext.dirs= -cp lib/*:out/production/jmavsim.jar me.drton.jmavsim.Simulator

Error:
Success!
3D [dev] 1.6.0-pre12-daily-experimental daily

libEGL warning: GLX/DRI2 is not supported
libGL error: failed to load driver: swrast
com.jogamp.opengl.GLException: X11GLXDrawableFactory - Could not initialize shared resources for X11GraphicsDevice[type .x11, connection localhost:10.0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x407df228, isOwner false, <ca5412c, 3559b630>[count 0, qsz 0, owner <NULL>]]]
        at jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:326)
        at jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:297)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.jogamp.opengl.GLException: main-SharedResourceRunner: Error making temp context(1) current: display 0x7faa4c006620, context 0x7faa4c038b40, drawable X11OnscreenGLXDrawable[Realized true,
        Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@3a80e41f,
        Handle    0x1200002,
        Surface   WrappedSurface[ displayHandle 0x7faa4c006620
, surfaceHandle 0x1200002
, size 64x64
, UOB[ OWNS_SURFACE | WINDOW_INVISIBLE ]
, X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection localhost:10.0, unitID 0, handle 0x7faa4c006620, owner true, ResourceToolkitLock[obj 0x6400cd3a, isOwner true, <70a1ce20, ee3d0a5>[count 2, qsz 0, owner <main-SharedResourceRunner>]]], idx 0], visualID 0x2e7, fbConfigID 0x4b,
        requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]],
        chosen    GLCaps[glx vid 0x2e7, fbc 0x4b: rgba 8/8/8/0, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL2/GL2.sw], on-scr[.]]]
, surfaceLock <e970846, 5da03325>[count 1, qsz 0, owner <main-SharedResourceRunner>]
, X11DummyUpstreamSurfaceHook[pixel 64x64]
, upstreamSurface false ]]
        at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:371)
        at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:759)
        at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:642)
        at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:580)
        at jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:297)
        ... 2 more
Exception in thread "main" java.lang.ExceptionInInitializerError
        at javax.media.j3d.GroupRetained.<init>(GroupRetained.java:155)
        at javax.media.j3d.TransformGroupRetained.<init>(TransformGroupRetained.java:116)
        at javax.media.j3d.TransformGroup.createRetained(TransformGroup.java:115)
        at javax.media.j3d.SceneGraphObject.<init>(SceneGraphObject.java:114)
        at javax.media.j3d.Node.<init>(Node.java:172)
        at javax.media.j3d.Group.<init>(Group.java:551)
        at javax.media.j3d.TransformGroup.<init>(TransformGroup.java:87)
        at me.drton.jmavsim.KinematicObject.<init>(KinematicObject.java:32)
        at me.drton.jmavsim.DynamicObject.<init>(DynamicObject.java:18)
        at me.drton.jmavsim.vehicle.AbstractVehicle.<init>(AbstractVehicle.java:23)
        at me.drton.jmavsim.vehicle.AbstractMulticopter.<init>(AbstractMulticopter.java:19)
        at me.drton.jmavsim.vehicle.Quadcopter.<init>(Quadcopter.java:32)
        at me.drton.jmavsim.Simulator.buildMulticopter(Simulator.java:184)
        at me.drton.jmavsim.Simulator.<init>(Simulator.java:116)
        at me.drton.jmavsim.Simulator.main(Simulator.java:387)
Caused by: com.jogamp.opengl.GLException: Profiles [GL4bc, GL3bc, GL2, GLES1] not available on device null
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:1038)
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:1049)
        at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:802)
        at javax.media.j3d.JoglPipeline.initialize(JoglPipeline.java:132)
        at javax.media.j3d.Pipeline.createPipeline(Pipeline.java:92)
        at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:837)
        at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:274)
        ... 15 more
X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 1/1, reusable (open, marked uncloseable): 0, pending (open in creation order): 1)
X11Util: Open X11 Display Connections: 1
X11Util: Open[0]: NamedX11Display[localhost:10.0, 0x7faa4c006620, refCount 1, unCloseable false]

**Comment by pranavn248** [comment]
Facing the same issue, did you get a fix for it?
